name: Caller Reusable Workflow Input Examples

on:
  - workflow_dispatch
  - push
    
jobs:
  use-kvp:
    uses: ./.github/workflows/rw-inputs.yml
    with:
      key-value-pairs: >
        key1: value1